bases:
  - ../environments.yaml
---
repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com

releases:
  - name: docker-secret
    chart: incubator/raw
    namespace: default
    values:
    - resources:
      {{- range $ns := env "NAMESPACES" | splitList "," }}
      - apiVersion: v1
        kind: Secret
        metadata:
          name: docker-secret
          namespace: {{ $ns }}
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: {{ env "DOCKER_SECRET" }}
      {{- end }}

